(()=>{
'use strict';
const D=window.TENKA_DATA;
const $=s=>document.querySelector(s);
const state={view:'home',level:'N5',mode:'vocab',cards:[],cardIndex:0,flipped:false,returnView:'level',quiz:null,timer:null,seconds:30,quizAnswered:false,kakijun:null,settings:load('tenka-settings',{sound:true,voice:true,meme:true,haptic:true}),progress:load('tenka-progress',{reviews:{},quizRuns:{},best:{},correct:0,total:0,streak:1,lastStudy:null})};
function load(k,f){try{const v=JSON.parse(localStorage.getItem(k));return v&&typeof v==='object'?Object.assign({},f,v):f}catch{return f}}
function save(){try{localStorage.setItem('tenka-progress',JSON.stringify(state.progress));localStorage.setItem('tenka-settings',JSON.stringify(state.settings))}catch{}}
function today(){return new Date().toISOString().slice(0,10)}
function markStudy(){const t=today();if(state.progress.lastStudy!==t){if(state.progress.lastStudy){const prev=new Date(state.progress.lastStudy+'T00:00:00');const now=new Date(t+'T00:00:00');state.progress.streak=Math.round((now-prev)/86400000)===1?(state.progress.streak||1)+1:1}else state.progress.streak=1;state.progress.lastStudy=t;save()}}
function toast(t){const el=$('#toast');if(!el)return;el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1300)}
function tapHaptic(ms=20){if(state.settings.haptic&&navigator.vibrate)navigator.vibrate(ms)}
function tone(kind='ok'){if(!state.settings.sound)return;try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);g.gain.setValueAtTime(.12,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.22);o.frequency.value=kind==='ok'?720:kind==='bad'?170:520;o.type=kind==='bad'?'sawtooth':'sine';o.start();o.stop(c.currentTime+.23)}catch{}}
function speak(text,rate=.9){if(!state.settings.voice||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ja-JP';u.rate=rate;speechSynthesis.speak(u)}
function feedback(ok){markStudy();tapHaptic(ok?18:55);tone(ok?'ok':'bad');if(state.settings.meme)setTimeout(()=>speak(ok?(Math.random()>.5?'正解！':'すごい！'):(Math.random()>.5?'えぇぇ！？':'惜しい！'),1.05),70)}
function startGreeting(){tone('ok');speak('今日も頑張ろう！');toast('今日も頑張ろう！')}
function top(title,sub=''){return `<div class="topbar"><div><div class="brand">${title}</div>${sub?`<div class="subtle">${sub}</div>`:''}</div><button class="icon-btn" onclick="startGreeting()">🔊</button></div>`}
function nav(){return `<nav class="bottom-nav"><button onclick="go('home')"><span>⌂</span>Home</button><button onclick="go('daily')"><span>🎯</span>Daily</button><button onclick="go('progress')"><span>📊</span>Progress</button><button onclick="go('settings')"><span>⚙️</span>Setting</button></nav>`}
function go(v){clearInterval(state.timer);state.timer=null;state.view=v;state.flipped=false;render();scrollTo(0,0)}
function render(){const a=$('#app');if(!a)return;const withNav=['home','jlpt','level','grammar','kaigo','handoff','daily','progress','settings'].includes(state.view);let html='';if(state.view==='home')html=home();if(state.view==='jlpt')html=jlpt();if(state.view==='level')html=level();if(state.view==='flash')html=flash();if(state.view==='grammar')html=grammar();if(state.view==='quiz')html=quizView();if(state.view==='kaigo')html=kaigo();if(state.view==='handoff')html=handoff();if(state.view==='kakijun')html=kakijun();if(state.view==='daily')html=daily();if(state.view==='progress')html=progress();if(state.view==='settings')html=settings();a.innerHTML=html+(withNav?nav():'')}
function home(){return `${top('TENKA 日本語','JLPT • Bunpou • Kaigo')}<section class="hero"><h1>今日も少しずつ。</h1><p>Belajar sedikit, tapi konsisten. Biar Jepang masuk kepala tanpa berasa baca buku tebal 😭</p><div class="streak">🔥 ${state.progress.streak||1} hari streak</div><div class="spacer"></div><button class="action primary" onclick="startGreeting()">始めよう！</button></section><div class="grid"><button class="nav-card" onclick="go('jlpt')"><div class="emoji">🈶</div><b>JLPT</b><span>N5 → N1 • kanji & kosakata</span></button><button class="nav-card" onclick="openGrammar('N5')"><div class="emoji">📝</div><b>Bunpou</b><span>Pola + penjelasan Indonesia</span></button><button class="nav-card" onclick="go('kaigo')"><div class="emoji">🏥</div><b>Kaigo</b><span>Kosakata medis & 申し送り</span></button><button class="nav-card" onclick="go('daily')"><div class="emoji">🎯</div><b>Daily Study</b><span>Misi singkat setiap hari</span></button></div><div class="install-tip">📱 Setelah TENKA di-host HTTPS: Safari → Share → <b>Add to Home Screen</b>.</div><div class="muted-box">V0.1 fokus membuktikan alur belajar. Materi N5 + Kaigo akan diperluas lebih dulu sebelum level lain.</div>`}
function countReviewed(level){const ids=[...D.jlpt[level].kanji,...D.jlpt[level].vocab].map(x=>x.id);return ids.filter(id=>state.progress.reviews[id]).length}
function jlpt(){const levels=['N5','N4','N3','N2','N1'];return `${top('JLPT','Pilih level — semua terbuka')}<button class="back" onclick="go('home')">←</button><div class="grid">${levels.map(l=>{const total=D.jlpt[l].kanji.length+D.jlpt[l].vocab.length,learned=countReviewed(l),pct=Math.round(learned/Math.max(1,total)*100);return `<button class="level-card" onclick="openLevel('${l}')"><div class="emoji">${l==='N5'?'🌱':l==='N4'?'🌿':l==='N3'?'🔥':l==='N2'?'⚡':'🏆'}</div><b>${l}</b><span>${learned}/${total} kartu disentuh</span><div class="progress"><i style="width:${pct}%"></i></div></button>`}).join('')}</div>`}
function openLevel(l){state.level=l;go('level')}
function level(){const d=D.jlpt[state.level],l=state.level;return `${top(l,`${d.kanji.length} kanji • ${d.vocab.length} kosakata • ${d.grammar.length} bunpou`)}<button class="back" onclick="go('jlpt')">←</button><div class="list"><button class="row" onclick="openFlash('${l}','kanji')"><div class="left"><b>🈶 Flashcard Kanji</b><small>Bentuk • bacaan • arti • contoh • kakijun</small></div><span>›</span></button><button class="row" onclick="openFlash('${l}','vocab')"><div class="left"><b>🔤 Flashcard Kosakata</b><small>SRS + audio</small></div><span>›</span></button><button class="row" onclick="openGrammar('${l}')"><div class="left"><b>📝 Bunpou ${l}</b><small>Penjelasan dalam bahasa Indonesia</small></div><span>›</span></button><button class="row" onclick="startQuiz('${l}','mix')"><div class="left"><b>🎮 Quiz 30 detik</b><small>Pilihan ganda + efek suara</small></div><span>›</span></button><button class="row" onclick="startQuiz('${l}','listening')"><div class="left"><b>🎧 Listening Quiz</b><small>Dengar Jepang → pilih arti</small></div><span>›</span></button></div>`}
function openFlash(l,m){state.level=l;state.mode=m;state.cards=[...D.jlpt[l][m]];state.cardIndex=0;state.flipped=false;state.returnView='level';go('flash')}
function schedule(c,rating){const days=rating==='again'?0:rating==='good'?3:7;state.progress.reviews[c.id]={rating,due:new Date(Date.now()+days*86400000).toISOString(),last:Date.now()};save();markStudy()}
function flash(){const c=state.cards[state.cardIndex];if(!c)return `<div class="score"><h2>Belum ada kartu.</h2><button class="action primary" onclick="go('${state.returnView}')">Kembali</button></div>`;const front=state.mode==='kanji'?`<div class="kanji">${c.kanji}</div>`:`<div class="term">${c.term}</div>`;const back=`<div class="reading">${c.reading||''}</div>${c.romaji?`<div class="subtle">${c.romaji}</div>`:''}<div class="meaning">${c.meaning}</div><div class="example"><b>${c.example||''}</b><br><small>${c.exampleReading||''}</small><br>${c.exampleMeaning||''}</div>`;return `<div class="topbar"><button class="back" onclick="go('${state.returnView}')">←</button><div class="subtle">${state.cardIndex+1}/${state.cards.length}</div><button class="icon-btn" onclick="speak('${esc(c.reading||c.term||c.kanji)}')">🔊</button></div><div class="flash-wrap"><div class="flash ${state.flipped?'flipped':''}" onclick="flipCard()"><div class="face">${front}<div class="subtle">Tap untuk balik</div></div><div class="face backface">${back}</div></div></div>${state.mode==='kanji'?`<div class="small-actions"><button class="pill" onclick="openKakijun('${c.id}')">✍️ Kakijun</button><button class="pill" onclick="speak('${esc(c.example||c.kanji)}')">🔊 Contoh</button></div><div class="spacer"></div>`:''}<div class="controls"><button class="action bad" onclick="rateCard('again')">😵 Lagi</button><button class="action blue" onclick="rateCard('good')">🙂 Hafal</button><button class="action ok" onclick="rateCard('easy')">✨ Mudah</button></div>`}
function esc(s){return String(s||'').replaceAll('\\','\\\\').replaceAll("'","\\'")}
function flipCard(){state.flipped=!state.flipped;const e=$('.flash');if(e)e.classList.toggle('flipped');tapHaptic(12)}
function rateCard(r){const c=state.cards[state.cardIndex];schedule(c,r);tone(r==='again'?'bad':'ok');state.cardIndex=(state.cardIndex+1)%state.cards.length;state.flipped=false;render()}
function openGrammar(l){state.level=l;go('grammar')}
function grammar(){const arr=D.jlpt[state.level].grammar;return `${top(`Bunpou ${state.level}`,'Pahami konteks, bukan cuma rumus')}<button class="back" onclick="go('level')">←</button>${arr.map(g=>`<article class="grammar-card"><span class="badge">${state.level}</span><h3>${g.title}</h3><div class="meaning">${g.meaning}</div><p>${g.explanation}</p><div class="pattern">${g.pattern}</div><div class="example"><b>${g.example}</b><br><small>${g.exampleReading||''}</small><br>${g.exampleMeaning}</div><p class="subtle">⚠️ ${g.contrast}</p><button class="action blue" onclick="speak('${esc(g.example)}')">🔊 Dengarkan contoh</button></article>`).join('')}`}
function allMeanings(){const a=[];Object.values(D.jlpt).forEach(x=>[...x.vocab,...x.kanji].forEach(c=>a.push(c.meaning)));return [...new Set(a)]}
function makeQuiz(level,type){let src=[...D.jlpt[level].vocab,...D.jlpt[level].kanji].sort(()=>Math.random()-.5).slice(0,10),all=allMeanings();return src.map(c=>{const wrong=all.filter(x=>x!==c.meaning).sort(()=>Math.random()-.5).slice(0,3),choices=[c.meaning,...wrong].sort(()=>Math.random()-.5);return{prompt:c.term||c.kanji,reading:c.reading,correct:c.meaning,choices,answer:choices.indexOf(c.meaning),type}})}
function startQuiz(l,type='mix'){state.level=l;state.returnView='level';state.quiz={items:makeQuiz(l,type),i:0,score:0,type};state.quizAnswered=false;go('quiz')}
function quizView(){const q=state.quiz;if(!q)return'';if(q.i>=q.items.length)return finishQuiz();const item=q.items[q.i];setTimeout(()=>{startTimer();if(q.type==='listening')speak(item.reading||item.prompt)},30);return `<div class="quiz-head"><button class="back" onclick="go('${state.returnView}')">←</button><b>${q.i+1}/${q.items.length}</b><div id="timer" class="timer">30</div></div><section class="question">${q.type==='listening'?`<div class="subtle">Dengarkan lalu pilih arti</div><div class="jp">🔊</div><button class="pill" onclick="speak('${esc(item.reading||item.prompt)}')">Putar lagi</button>`:`<div class="subtle">Apa arti kata ini?</div><div class="jp">${item.prompt}</div><div class="subtle">${item.reading||''}</div>`}</section><div class="choices">${item.choices.map((c,i)=>`<button id="choice-${i}" class="choice" onclick="answerQuiz(${i})">${String.fromCharCode(65+i)}. ${c}</button>`).join('')}</div>`}
function startTimer(){clearInterval(state.timer);state.seconds=30;const el=$('#timer');state.timer=setInterval(()=>{state.seconds--;if(el){el.textContent=state.seconds;if(state.seconds<=5)el.classList.add('danger')}if(state.seconds<=0){clearInterval(state.timer);answerQuiz(-1)}},1000)}
function answerQuiz(i){if(state.quizAnswered)return;state.quizAnswered=true;clearInterval(state.timer);const item=state.quiz.items[state.quiz.i],ok=i===item.answer;state.progress.total++;if(ok){state.quiz.score++;state.progress.correct++}save();feedback(ok);item.choices.forEach((_,n)=>{const b=$(`#choice-${n}`);if(b){if(n===item.answer)b.classList.add('correct');else if(n===i)b.classList.add('wrong')}});setTimeout(()=>{state.quiz.i++;state.quizAnswered=false;render()},850)}
function finishQuiz(){const q=state.quiz,key=`${state.level}-${q.type}`,pct=Math.round(q.score/Math.max(1,q.items.length)*100);state.progress.quizRuns[key]=(state.progress.quizRuns[key]||0)+1;state.progress.best[key]=Math.max(state.progress.best[key]||0,pct);save();setTimeout(()=>{tone('ok');speak(pct>=70?'おめでとうございます！':'お疲れさまでした！')},120);return `<div class="score"><div class="confetti">🎉✨🎊</div><div class="mega">${pct}%</div><h2>${pct>=90?'すごい！':pct>=70?'おめでとうございます！':'もう一回！'}</h2><p>${q.score}/${q.items.length} benar</p><button class="action primary" onclick="restartQuiz()">Main lagi</button> <button class="action" onclick="go('${state.returnView}')">Selesai</button></div>`}
function restartQuiz(){state.level==='KAIGO'?startKaigoQuiz():startQuiz(state.level,state.quiz.type)}
function kaigo(){const cats=[...new Set(D.kaigo.vocab.map(x=>x.category))];return `${top('Kaigo・Keperawatan','Tidak pakai level JLPT')}<button class="back" onclick="go('home')">←</button><div class="list"><button class="row" onclick="openKaigoFlash()"><div class="left"><b>🏥 Flashcard Kaigo</b><small>${D.kaigo.vocab.length} istilah awal</small></div><span>›</span></button><button class="row" onclick="startKaigoQuiz()"><div class="left"><b>🎮 Quiz Kaigo</b><small>Kosakata rumah sakit</small></div><span>›</span></button><button class="row" onclick="go('handoff')"><div class="left"><b>🗣️ 申し送り Practice</b><small>Dengar konteks operan</small></div><span>›</span></button></div><div class="section-title">Kategori</div><div class="small-actions">${cats.map(x=>`<span class="pill">${x}</span>`).join('')}</div>`}
function openKaigoFlash(){state.cards=[...D.kaigo.vocab];state.mode='vocab';state.cardIndex=0;state.flipped=false;state.returnView='kaigo';go('flash')}
function startKaigoQuiz(){const pool=[...D.kaigo.vocab],items=pool.sort(()=>Math.random()-.5).slice(0,10).map(c=>{const wrong=pool.filter(x=>x.id!==c.id).sort(()=>Math.random()-.5).slice(0,3).map(x=>x.meaning),choices=[c.meaning,...wrong].sort(()=>Math.random()-.5);return{prompt:c.term,reading:c.reading,choices,answer:choices.indexOf(c.meaning),type:'kaigo'}});state.level='KAIGO';state.returnView='kaigo';state.quiz={items,i:0,score:0,type:'kaigo'};state.quizAnswered=false;go('quiz')}
function handoff(){return `${top('申し送り Practice','Baca → dengar → tangkap inti')}<button class="back" onclick="go('kaigo')">←</button>${D.kaigo.handoff.map(h=>`<article class="grammar-card"><div class="handoff">${h.text}</div><div class="furigana">${h.reading}</div><div class="example">🇮🇩 ${h.meaning}</div><div class="small-actions"><button class="pill" onclick="speak('${esc(h.text)}')">🔊 Normal</button><button class="pill" onclick="speak('${esc(h.text)}',.68)">🐢 Pelan</button></div><h3 style="font-size:18px">${h.question}</h3><div class="choices">${h.choices.map((c,i)=>`<button class="choice" onclick="handoffAnswer(this,${i===h.answer})">${c}</button>`).join('')}</div></article>`).join('')}`}
function handoffAnswer(btn,ok){btn.classList.add(ok?'correct':'wrong');feedback(ok);toast(ok?'正解！':'惜しい！')}
function findCard(id){for(const l of Object.keys(D.jlpt)){const c=D.jlpt[l].kanji.find(x=>x.id===id);if(c)return c}return null}
function openKakijun(id){state.kakijun=findCard(id);if(state.kakijun)go('kakijun')}
function kakijun(){const c=state.kakijun,has=c.strokes&&c.strokes.length;setTimeout(()=>{if(has)animateStrokes();setupCanvas()},40);return `<div class="topbar"><button class="back" onclick="go('flash')">←</button><div><b>書き順 Kakijun</b><div class="subtle">${c.kanji} • ${has?c.strokes.length+' goresan':'stroke belum tersedia'}</div></div><button class="icon-btn" onclick="animateStrokes()">▶️</button></div>${has?`<div class="kanji-stage"><svg viewBox="0 0 100 100">${c.strokes.map((p,i)=>`<path class="stroke" data-i="${i}" d="${p}"/>`).join('')}</svg></div>`:`<div class="muted-box">Data stroke akurat belum dimasukkan untuk kanji ini. Nanti kita integrasikan dataset kakijun terverifikasi.</div>`}<div class="section-title">✍️ Coba tulis dengan jari</div><div class="canvas-wrap"><canvas id="writeCanvas" width="650" height="420"></canvas></div><div class="small-actions" style="margin-top:10px"><button class="pill" onclick="clearCanvas()">Hapus</button><button class="pill" onclick="toggleGuide()">Tampilkan contoh</button></div>`}
function animateStrokes(){document.querySelectorAll('.stroke').forEach((p,i)=>{p.classList.remove('animate');void p.offsetWidth;setTimeout(()=>p.classList.add('animate'),i*620)})}
let drawing=false,ctx,guide=false;
function setupCanvas(){const c=$('#writeCanvas');if(!c)return;ctx=c.getContext('2d');ctx.lineWidth=12;ctx.lineCap='round';ctx.strokeStyle='#111';const pos=e=>{const r=c.getBoundingClientRect();return[(e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height]};c.onpointerdown=e=>{e.preventDefault();drawing=true;const[x,y]=pos(e);ctx.beginPath();ctx.moveTo(x,y)};c.onpointermove=e=>{if(!drawing)return;e.preventDefault();const[x,y]=pos(e);ctx.lineTo(x,y);ctx.stroke()};c.onpointerup=c.onpointerleave=()=>drawing=false}
function clearCanvas(){const c=$('#writeCanvas');if(ctx)ctx.clearRect(0,0,c.width,c.height);if(guide)drawGuide()}
function toggleGuide(){guide=!guide;clearCanvas()}
function drawGuide(){const c=$('#writeCanvas');if(!ctx||!state.kakijun)return;ctx.save();ctx.globalAlpha=.12;ctx.fillStyle='#111';ctx.font='300px serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(state.kakijun.kanji,c.width/2,c.height/2+10);ctx.restore()}
function daily(){const reviewed=Object.keys(state.progress.reviews).length,runs=Object.values(state.progress.quizRuns).reduce((a,b)=>a+b,0),missions=[['🈶 Review kartu',5,Math.min(5,reviewed)],['🏥 Kaigo',5,Math.min(5,state.progress.quizRuns['KAIGO-kaigo']||0)],['🎮 Quiz',1,runs?1:0]];return `${top('今日のミッション','Target kecil supaya gampang mulai')}<button class="back" onclick="go('home')">←</button>${missions.map(m=>`<div class="mission"><div class="mission-line"><b>${m[0]}</b><span>${m[2]}/${m[1]}</span></div><div class="progress"><i style="width:${Math.min(100,m[2]/m[1]*100)}%"></i></div></div>`).join('')}<button class="action primary" onclick="openLevel('N5')">Mulai 5 menit →</button>`}
function progress(){const runs=Object.values(state.progress.quizRuns).reduce((a,b)=>a+b,0),acc=state.progress.total?Math.round(state.progress.correct/state.progress.total*100):0;return `${top('Progress','Tersimpan di perangkat ini')}<button class="back" onclick="go('home')">←</button><div class="grid"><div class="nav-card"><div class="emoji">🔥</div><b>${state.progress.streak||1}</b><span>day streak</span></div><div class="nav-card"><div class="emoji">🎮</div><b>${runs}</b><span>quiz dimainkan</span></div><div class="nav-card"><div class="emoji">🎯</div><b>${acc}%</b><span>akurasi quiz</span></div><div class="nav-card"><div class="emoji">🧠</div><b>${Object.keys(state.progress.reviews).length}</b><span>kartu direview</span></div></div><div class="section-title">Per level</div>${['N5','N4','N3','N2','N1'].map(l=>`<div class="row"><div><b>${l}</b><small>${countReviewed(l)} kartu direview</small></div><span>${state.progress.best[`${l}-mix`]||0}% best</span></div>`).join('')}`}
function settings(){const s=state.settings;return `${top('Settings','Seru di rumah, bisa dibuat tenang saat kerja')}<button class="back" onclick="go('home')">←</button>${toggle('sound','🔊 Sound effect','Benar/salah/tombol',s.sound)}${toggle('voice','🗣️ Voice Jepang','Speech synthesis ja-JP',s.voice)}${toggle('meme','😂 Meme Mode','えぇぇ！？・惜しい！・すごい！',s.meme)}${toggle('haptic','📳 Haptic','Jika browser mendukung',s.haptic)}<div class="spacer"></div><button class="action bad" onclick="resetProgress()">Reset progress</button>`}
function toggle(k,title,sub,on){return `<div class="toggle"><div><b>${title}</b><div class="subtle">${sub}</div></div><input type="checkbox" ${on?'checked':''} onchange="setSetting('${k}',this.checked)"></div>`}
function setSetting(k,v){state.settings[k]=v;save();toast('Tersimpan')}
function resetProgress(){if(confirm('Reset semua progress lokal?')){localStorage.removeItem('tenka-progress');state.progress={reviews:{},quizRuns:{},best:{},correct:0,total:0,streak:1,lastStudy:null};render()}}
Object.assign(window,{startGreeting,go,openLevel,openFlash,flipCard,rateCard,openGrammar,speak,startQuiz,answerQuiz,restartQuiz,openKaigoFlash,startKaigoQuiz,handoffAnswer,openKakijun,animateStrokes,clearCanvas,toggleGuide,setSetting,resetProgress});
render();
window.TENKA_READY=true;
})();
