(()=>{
'use strict';
const DB_NAME='tenka-audio-v1';
const STORE='clips';
const memory={};
const lastByEvent={};
let nativeSpeak=null;
let combo=0;
const reactionTextToEvent={'今日も頑張ろう！':'greeting','正解！':'correct','すごい！':'correct','えぇぇ！？':'wrong','惜しい！':'wrong','おめでとうございます！':'finish','お疲れさまでした！':'finish'};
const phrases={greeting:['今日も頑張ろう！','よーし、始めよう！','今日も一緒に頑張ろう！'],correct:['正解！','やったー！','すごい！','いいね！','その調子！','完璧！'],wrong:['惜しい！','ざんねーん！','えぇぇ！？','もう一回！','ドンマイ！'],combo:['すごいすごい！','その調子！','止まらないね！','天才かも！'],finish:['おめでとう！','お疲れさま！','よく頑張ったね！'],perfect:['全問正解！すごい！','パーフェクト！おめでとう！','完璧！天才！']};
function openDb(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window)){resolve(null);return}const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'id'});s.createIndex('event','event',{unique:false})}};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function addMemory(item){if(!item||!item.event||!item.blob)return;if(!memory[item.event])memory[item.event]=[];memory[item.event].push({id:item.id,name:item.name||'Custom',url:URL.createObjectURL(item.blob)})}
async function loadCustom(){try{const db=await openDb();if(!db)return;const items=await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly');const req=tx.objectStore(STORE).getAll();req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error)});items.forEach(addMemory)}catch{}}
function choose(arr,event){if(!arr||!arr.length)return null;let pool=arr;const last=lastByEvent[event];if(arr.length>1&&last)pool=arr.filter(x=>(x.id||x)!==last);const pick=pool[Math.floor(Math.random()*pool.length)];lastByEvent[event]=pick.id||pick;return pick}
function japaneseVoice(){if(!('speechSynthesis'in window))return null;const vs=speechSynthesis.getVoices().filter(v=>/^ja(-|_)/i.test(v.lang||''));return vs[0]||null}
function expressiveSpeak(text){if(!text||!nativeSpeak||!('SpeechSynthesisUtterance'in window))return;try{const u=new SpeechSynthesisUtterance(text);u.lang='ja-JP';const v=japaneseVoice();if(v)u.voice=v;u.rate=.98+Math.random()*.12;u.pitch=1.18+Math.random()*.2;nativeSpeak(u)}catch{}}
function play(event){const custom=choose(memory[event],event);if(custom){try{const a=new Audio(custom.url);a.volume=1;const p=a.play();if(p&&p.catch)p.catch(()=>fallback(event));return}catch{}}fallback(event)}
function fallback(event){const phrase=choose(phrases[event]||[],event);if(phrase)expressiveSpeak(phrase)}
async function importFiles(event,fileList){const files=[...(fileList||[])].filter(f=>f&&/^audio\//.test(f.type||''));if(!files.length)return 0;try{const db=await openDb();if(!db)return 0;let saved=0;for(const file of files){const item={id:event+':'+Date.now()+':'+Math.random().toString(36).slice(2),event,name:file.name,blob:file};await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(item);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});addMemory(item);saved++}return saved}catch{return 0}}
async function clearEvent(event){try{(memory[event]||[]).forEach(x=>URL.revokeObjectURL(x.url));memory[event]=[];const db=await openDb();if(!db)return;const ids=await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly');const req=tx.objectStore(STORE).index('event').getAllKeys(event);req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error)});await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');ids.forEach(id=>tx.objectStore(STORE).delete(id));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}catch{}}
function count(event){return(memory[event]||[]).length}
function toast(t){const el=document.querySelector('#toast');if(!el)return;el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1500)}
async function importFromInput(event,input){const n=await importFiles(event,input&&input.files);toast(n?`${n} suara ditambahkan`:'File audio tidak terbaca');injectSettings(true)}
async function clearFromSettings(event){await clearEvent(event);toast('Sound custom dihapus');injectSettings(true)}
function row(event,label){const n=count(event);return `<div class="row"><div><b>${label}</b><small>${n} suara custom</small></div><div class="small-actions"><label class="pill">＋ Tambah<input type="file" accept="audio/*" multiple style="display:none" onchange="tenkaImportSound('${event}',this)"></label>${n?`<button class="pill" onclick="tenkaClearSound('${event}')">Hapus</button>`:''}</div></div>`}
function injectSettings(force=false){const app=document.querySelector('#app');if(!app||!app.textContent.includes('Settings'))return;let box=document.querySelector('#tenka-custom-sounds');if(box&&!force)return;if(box)box.remove();box=document.createElement('section');box.id='tenka-custom-sounds';box.innerHTML=`<div class="section-title">🎵 Custom Anime / Meme Sound</div><div class="muted-box">Pilih audio dari Files iPhone. File disimpan lokal di perangkat ini dan tidak di-upload ke GitHub.</div>${row('correct','✅ Benar')}${row('wrong','❌ Salah')}${row('combo','🔥 Combo')}${row('finish','🎉 Selesai')}${row('greeting','👋 Mulai belajar')}`;const danger=[...app.querySelectorAll('button')].find(b=>b.textContent.includes('Reset progress'));if(danger&&danger.parentNode)danger.parentNode.insertBefore(box,danger);else app.appendChild(box)}
function patchSpeech(){if(!('speechSynthesis'in window)||nativeSpeak)return;nativeSpeak=speechSynthesis.speak.bind(speechSynthesis);try{speechSynthesis.speak=function(utterance){const text=utterance&&utterance.text;const event=reactionTextToEvent[text];if(event){play(event);return}return nativeSpeak(utterance)}}catch{}}
function patchNavigation(){if(typeof window.go==='function'&&!window.go.__tenkaAudioPatched){const original=window.go;const wrapped=function(v){const r=original.apply(this,arguments);if(v==='settings')setTimeout(()=>injectSettings(),0);return r};wrapped.__tenkaAudioPatched=true;window.go=wrapped}if(typeof window.answerQuiz==='function'&&!window.answerQuiz.__tenkaAudioPatched){const original=window.answerQuiz;const wrapped=function(i){const r=original.apply(this,arguments);setTimeout(()=>{if(i<0){combo=0;return}const b=document.querySelector('#choice-'+i);if(b&&b.classList.contains('correct')){combo++;if(combo>=3&&combo%3===0)play('combo')}else combo=0},20);return r};wrapped.__tenkaAudioPatched=true;window.answerQuiz=wrapped}if(typeof window.restartQuiz==='function'&&!window.restartQuiz.__tenkaAudioPatched){const original=window.restartQuiz;const wrapped=function(){combo=0;return original.apply(this,arguments)};wrapped.__tenkaAudioPatched=true;window.restartQuiz=wrapped}}
function init(){patchSpeech();patchNavigation();loadCustom();if('speechSynthesis'in window)speechSynthesis.getVoices();setTimeout(injectSettings,100)}
window.TENKA_AUDIO={play,importFiles,clearEvent,count};window.tenkaImportSound=importFromInput;window.tenkaClearSound=clearFromSettings;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0));else setTimeout(init,0);
})();
