(()=>{
'use strict';
const D=window.TENKA_DATA;if(!D||!D.jlpt||!D.jlpt.N5)return;

const n5Grammar=[
{id:'n5-g-26',title:'～です／だ',meaning:'adalah / merupakan / bentuk penutup kalimat nominal',pattern:'N・Aな + です（sopan）／だ（biasa）',explanation:'です dan だ dipakai sebagai copula untuk menyatakan atau mengidentifikasi sesuatu. です adalah bentuk sopan, sedangkan だ adalah bentuk biasa/plain yang lebih langsung.',usage:'Membuat pernyataan seperti “saya mahasiswa”, “tempat ini tenang”, atau menyatakan identitas dan keadaan dengan nomina/kata sifat-na.',whenToUse:'Gunakan です dalam percakapan sopan dan situasi kerja. Gunakan だ terutama dalam gaya biasa dengan teman dekat, catatan, atau gaya yang memang plain.',watchOut:'Jangan menambahkan だ setelah kata sifat-i. Benar: 寒いです／寒い. Salah: 寒いだ. Untuk nomina dan kata sifat-na, だ bisa dipakai dalam bentuk biasa: 学生だ、静かだ.',commonMistake:'Mengira です selalu berarti “adalah” secara harfiah atau menempelkan だ ke semua kata. Fungsi copula bergantung jenis kata dan tingkat kesopanan.',example:'私は会社員です。',exampleReading:'わたし は かいしゃいん です。',exampleMeaning:'Saya adalah karyawan perusahaan.',extraExample:'この部屋は静かだ。',extraExampleReading:'この へや は しずか だ。',extraExampleMeaning:'Kamar ini tenang. (gaya biasa/plain)',contrast:'です = sopan; だ = plain. Kata sifat-i tidak memakai だ: おいしいです／おいしい, bukan おいしいだ。'},
{id:'n5-g-27',title:'～は',meaning:'penanda topik / “kalau soal ～”',pattern:'Topik + は + keterangan',explanation:'Partikel は menandai topik yang sedang dibicarakan. Saat menjadi partikel, は dibaca “wa”. は juga dapat memberi nuansa kontras.',usage:'Menentukan “kita sedang membicarakan apa” lalu memberi informasi tentang topik tersebut.',whenToUse:'Gunakan saat memperkenalkan atau melanjutkan topik yang sudah jelas, misalnya 私はインドネシア人です. は juga dapat membandingkan/menonjolkan perbedaan tergantung konteks.',watchOut:'は bukan sekadar “penanda subjek”. Subjek gramatikal sering ditandai が. Dalam satu kalimat keduanya bahkan dapat muncul bersama, jadi jangan mengganti は dan が secara mekanis.',commonMistake:'Membaca partikel は sebagai “ha” atau menganggap semua subjek harus memakai は. Saat berfungsi sebagai partikel topik, bacaannya “wa”.',example:'私はインドネシア人です。',exampleReading:'わたし は インドネシアじん です。',exampleMeaning:'Saya orang Indonesia.',extraExample:'コーヒーは飲みますが、お酒は飲みません。',extraExampleReading:'コーヒー は のみます が、おさけ は のみません。',extraExampleMeaning:'Kopi saya minum, tetapi alkohol tidak saya minum. Di sini は memberi kontras.',contrast:'は menyorot topik/kontras; が lebih sering menandai atau mengidentifikasi subjek/informasi yang difokuskan.'},
{id:'n5-g-28',title:'～が',meaning:'penanda subjek / identifikasi',pattern:'Subjek + が + predikat',explanation:'Partikel が menandai subjek atau unsur yang diidentifikasi sebagai pelaku, keberadaan, atau fokus informasi tertentu.',usage:'Menunjukkan siapa/apa yang melakukan, ada, atau menjadi jawaban fokus; juga muncul dalam pola seperti ～が好きです dan ～があります／います.',whenToUse:'Sering dipakai saat memperkenalkan informasi baru, menjawab pertanyaan “siapa/apa?”, atau pada pola yang memang menuntut が.',watchOut:'Jangan menganggap が selalu dapat diganti は. Nuansanya berbeda: は menetapkan topik, sedangkan が cenderung memfokuskan atau mengidentifikasi unsur sebelum が.',commonMistake:'Memilih は dan が hanya berdasarkan terjemahan Indonesia. Contoh: 誰が来ますか → 田中さんが来ます; が menandai Tanaka sebagai jawaban “siapa yang datang”.',example:'猫がいます。',exampleReading:'ねこ が います。',exampleMeaning:'Ada kucing.',extraExample:'誰が来ますか。田中さんが来ます。',extraExampleReading:'だれ が きます か。たなかさん が きます。',extraExampleMeaning:'Siapa yang datang? Tanaka-san yang datang.',contrast:'は = topik/kontras; が = subjek atau unsur yang difokuskan/diidentifikasi. Perbedaannya sangat bergantung konteks.'},
{id:'n5-g-29',title:'～を',meaning:'penanda objek langsung',pattern:'Objek + を + V',explanation:'Partikel を menandai benda atau hal yang menjadi sasaran langsung suatu tindakan. Sebagai partikel, を dibaca “o”.',usage:'Menunjukkan apa yang dimakan, diminum, dibaca, dilihat, dibeli, dan tindakan transitif lainnya.',whenToUse:'Gunakan sebelum verba yang melakukan tindakan terhadap objek, misalnya 水を飲みます、本を読みます、テレビを見ます.',watchOut:'Tidak semua kata yang terasa seperti “objek” dalam bahasa Indonesia memakai を dalam bahasa Jepang. Beberapa pola memakai が atau に, misalnya 日本語が好きです dan 電車に乗ります.',commonMistake:'Memakai を karena terjemahan Indonesia terasa punya objek. Partikel harus mengikuti pola verba/ungkapan Jepang, bukan struktur Indonesia secara mentah.',example:'水を飲みます。',exampleReading:'みず を のみます。',exampleMeaning:'Saya minum air.',extraExample:'毎晩、本を読みます。',extraExampleReading:'まいばん、ほん を よみます。',extraExampleMeaning:'Setiap malam saya membaca buku.',contrast:'を menandai objek tindakan; が biasanya menandai subjek/fokus, sedangkan に sering menandai tujuan, waktu, lokasi keberadaan, atau target.'},
{id:'n5-g-30',title:'～に',meaning:'ke / pada / di / target atau titik tujuan',pattern:'N + に + V',explanation:'Partikel に memiliki beberapa fungsi dasar N5: menandai tujuan gerak, waktu tertentu, lokasi keberadaan, atau target sebuah tindakan. Benang merahnya sering berupa titik tujuan/end-point.',usage:'Menandai “ke mana”, “kapan”, “di mana sesuatu berada”, atau “kepada siapa/apa” suatu tindakan diarahkan.',whenToUse:'Contoh utama: 学校に行きます (tujuan), 七時に起きます (waktu), 部屋に人がいます (lokasi keberadaan), 先生に聞きます (target).',watchOut:'Jangan tertukar dengan で untuk tempat aktivitas. 病院で働きます = bekerja di rumah sakit; 病院にいます = berada di rumah sakit. Beberapa keterangan waktu seperti 今日・明日 biasanya tidak memerlukan に.',commonMistake:'Menggunakan に untuk semua arti “di”. Pilih berdasarkan fungsi: keberadaan/tujuan/waktu/target sering memakai に, sedangkan lokasi sebuah aktivitas biasanya memakai で.',example:'学校に行きます。',exampleReading:'がっこう に いきます。',exampleMeaning:'Saya pergi ke sekolah.',extraExample:'七時に起きます。',extraExampleReading:'しちじ に おきます。',extraExampleMeaning:'Saya bangun pukul tujuh.',contrast:'に menandai tujuan, titik waktu, lokasi keberadaan, atau target; で menandai tempat berlangsungnya aktivitas atau alat/cara.'}
];

function pushUnique(target,items){const ids=new Set(target.map(x=>x.id));for(const item of items){if(!ids.has(item.id)){target.push(item);ids.add(item.id)}}}
pushUnique(D.jlpt.N5.grammar,n5Grammar);
})();